console.log('\x1b[31m%s\x1b[0m', 'Text in Rot');
console.log('\x1b[32m%s\x1b[0m', 'Text in Grün');
console.log('\x1b[33m%s\x1b[0m', 'Text in Gelb');
console.log('\x1b[34m%s\x1b[0m', 'Text in Blau');
console.log('\x1b[35m%s\x1b[0m', 'Text in Magenta');
console.log('\x1b[36m%s\x1b[0m', 'Text in Cyan');
console.log('\x1b[37m%s\x1b[0m', 'Text in Weiß');
console.log('\x1b[41m%s\x1b[0m', 'Hintergrund in Rot');
console.log('\x1b[42m%s\x1b[0m', 'Hintergrund in Grün');
console.log('\x1b[43m%s\x1b[0m', 'Hintergrund in Gelb');
console.log('\x1b[44m%s\x1b[0m', 'Hintergrund in Blau');
console.log('\x1b[45m%s\x1b[0m', 'Hintergrund in Magenta');
console.log('\x1b[46m%s\x1b[0m', 'Hintergrund in Cyan');
console.log('\x1b[47m%s\x1b[0m', 'Hintergrund in Weiß');
console.log('\x1b[91m%s\x1b[0m', 'Heller Text in Rot');
console.log('\x1b[92m%s\x1b[0m', 'Heller Text in Grün');
console.log('\x1b[93m%s\x1b[0m', 'Heller Text in Gelb');
console.log('\x1b[94m%s\x1b[0m', 'Heller Text in Blau');
console.log('\x1b[95m%s\x1b[0m', 'Heller Text in Magenta');
console.log('\x1b[96m%s\x1b[0m', 'Heller Text in Cyan');
console.log('\x1b[97m%s\x1b[0m', 'Heller Text in Weiß');

console.log('\x1b[101m%s\x1b[0m', 'Heller Hintergrund in Rot');
console.log('\x1b[102m%s\x1b[0m', 'Heller Hintergrund in Grün');
console.log('\x1b[103m%s\x1b[0m', 'Heller Hintergrund in Gelb');
console.log('\x1b[104m%s\x1b[0m', 'Heller Hintergrund in Blau');
console.log('\x1b[105m%s\x1b[0m', 'Heller Hintergrund in Magenta');
console.log('\x1b[106m%s\x1b[0m', 'Heller Hintergrund in Cyan');

console.log('\x1b[107m%s\x1b[0m', 'Heller Hintergrund in Weiß');
console.log('\x1b[1m\x1b[31m%s\x1b[0m', 'Fetter roter Text');
console.log('\x1b[4m\x1b[34m%s\x1b[0m', 'Unterstrichener blauer Text');